pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image '3.9.9-eclipse-temurin-11' }
      }
      steps {
        sh 'maven --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:23-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
